// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBy48dsWcvprnvXaDb5GdQpchRQBkoPK0',
    appId: '1:852829412127:web:cb59d47f26536bed036e2a',
    messagingSenderId: '852829412127',
    projectId: 'projet-2cp-1539a',
    authDomain: 'projet-2cp-1539a.firebaseapp.com',
    storageBucket: 'projet-2cp-1539a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHj0HpTZC3oqhpQjAYahNK6Pa3es2vXos',
    appId: '1:852829412127:android:c697a5cdfbc48a2a036e2a',
    messagingSenderId: '852829412127',
    projectId: 'projet-2cp-1539a',
    storageBucket: 'projet-2cp-1539a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCHr7x0Fy3FpLlCdss-ZA_ymGGX3GQvzQ',
    appId: '1:852829412127:ios:a12717e2330ccc08036e2a',
    messagingSenderId: '852829412127',
    projectId: 'projet-2cp-1539a',
    storageBucket: 'projet-2cp-1539a.appspot.com',
    iosClientId: '852829412127-fh6bt7b8h05nmutt8to2h9kvnsg5pk9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCHr7x0Fy3FpLlCdss-ZA_ymGGX3GQvzQ',
    appId: '1:852829412127:ios:a12717e2330ccc08036e2a',
    messagingSenderId: '852829412127',
    projectId: 'projet-2cp-1539a',
    storageBucket: 'projet-2cp-1539a.appspot.com',
    iosClientId: '852829412127-fh6bt7b8h05nmutt8to2h9kvnsg5pk9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
